name: Docker CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # 1. Faz checkout do código
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Configura o Docker Buildx
      - name: Configurando Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 3. Faz login no Docker Hub (ou outro registry)
      - name: Fazendo login no Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      # 4. Constrói a imagem Docker
      - name: Construindo Docker image
        run: docker build -t implementacao .

      # 5. Executa testes dentro do contêiner
      - name: Executando testes
        run: docker run implementacao python -m pytest

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest

    steps:
      # 1. Faz checkout do código
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Configura o Docker Buildx
      - name: Configurando Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 3. Faz login no Docker Hub
      - name: Fazendo login no Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      # 4. Constrói e envia a imagem Docker para o Docker Hub
      - name: Enviando imagem para o Docker Hub
        run: |
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/implementacao:latest .
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/implementacao:latest
